cache:
  key: ${CI_PROJECT_ID}
  paths:
    - .gradle/

before_script:
  - export GRADLE_USER_HOME=$(pwd)/.gradle
  - chmod +x ./gradlew

test:
  type: test
  script:
    - source /etc/profile
    - ./gradlew spoonDebugAndroidTest
  artifacts:
    paths:
    - app/build/